/****************************************************************************
**
** This code was generated by a code generator based on imatix/gsl
** Any changes in this code will be lost.
**
****************************************************************************/
#ifndef MACHINETALK_PUBLISH_H
#define MACHINETALK_PUBLISH_H
#include <QObject>
#include <QStateMachine>
#include <nzmqt/nzmqt.hpp>
#include <machinetalk/protobuf/message.pb.h>
#include <google/protobuf/text_format.h>

#if defined(Q_OS_IOS)
namespace gpb = google_public::protobuf;
#else
namespace gpb = google::protobuf;
#endif

using namespace nzmqt;

class MachinetalkPublish : public QObject
{
    Q_OBJECT
    Q_PROPERTY(bool ready READ ready WRITE setReady NOTIFY readyChanged)
    Q_PROPERTY(QString socketUri READ socketUri WRITE setSocketUri NOTIFY socketUriChanged)
    Q_PROPERTY(QString debugName READ debugName WRITE setDebugName NOTIFY debugNameChanged)
    Q_PROPERTY(State state READ state NOTIFY stateChanged)
    Q_PROPERTY(QString errorString READ errorString NOTIFY errorStringChanged)
    Q_ENUMS(State)

public:
    explicit MachinetalkPublish(QObject *parent = 0);
    ~MachinetalkPublish();

    enum State {
        Down = 0,
        Up = 1,
    };

    QString socketUri() const
    {
        return m_socketUri;
    }

    QString debugName() const
    {
        return m_debugName;
    }

    State state() const
    {
        return m_state;
    }

    QString errorString() const
    {
        return m_errorString;
    }

    bool ready() const
    {
        return m_ready;
    }

public slots:

    void setSocketUri(QString uri)
    {
        if (m_socketUri == uri)
            return;

        m_socketUri = uri;
        emit socketUriChanged(uri);
    }

    void setDebugName(QString debugName)
    {
        if (m_debugName == debugName)
            return;

        m_debugName = debugName;
        emit debugNameChanged(debugName);
    }

    void setReady(bool ready)
    {
        if (m_ready == ready)
            return;

        m_ready = ready;
        emit readyChanged(ready);

        if (m_ready)
        {
            start();
        }
        else
        {
            stop();
        }
    }

    void sendSocketMessage(const QByteArray &topic, pb::ContainerType type, pb::Container *tx);

private:
    bool m_ready;
    QString m_socketUri;
    QString m_debugName;

    SocketNotifierZMQContext *m_context;
    ZMQSocket  *m_socket;

    State         m_state;
    QStateMachine *m_fsm;
    QString       m_errorString;
    // more efficient to reuse a protobuf Messages
    pb::Container m_socketTx;

    void start();
    void stop();

private slots:

    bool connectSockets();
    void disconnectSockets();

    void socketError(int errorNum, const QString& errorMsg);

    void sendPing(const QByteArray &topic);

    void fsmDownEntered();
    void fsmUpEntered();

signals:

    void socketUriChanged(QString uri);
    void debugNameChanged(QString debugName);
    void stateChanged(MachinetalkPublish::State state);
    void errorStringChanged(QString errorString);
    void readyChanged(bool ready);
    // fsm
    void fsmConnect();
    void fsmDisconnect();
};

#endif //MACHINETALK_PUBLISH_H
